"""Fixing models

Revision ID: 0bc22e841fad
Revises: 05402ffff46a
Create Date: 2026-01-09 14:31:29.912806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bc22e841fad'
down_revision: Union[str, Sequence[str], None] = '05402ffff46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_user')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.drop_index(op.f('ix_groupmembers_group_id'), table_name='groupmembers')
    op.drop_table('groupmembers')
    op.add_column('followers', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.add_column('followers', sa.Column('subscriber_id', sa.Integer(), nullable=False))
    op.add_column('followers', sa.Column('is_subscribed', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_followers_channel'), table_name='followers')
    op.drop_index(op.f('ix_followers_subscriber'), table_name='followers')
    op.drop_constraint(op.f('unique_channel_subscriber'), 'followers', type_='unique')
    op.create_index(op.f('ix_followers_channel_id'), 'followers', ['channel_id'], unique=False)
    op.create_index(op.f('ix_followers_subscriber_id'), 'followers', ['subscriber_id'], unique=False)
    op.create_unique_constraint('uq_channel_subscriber', 'followers', ['channel_id', 'subscriber_id'])
    op.drop_constraint(op.f('followers_channel_fkey'), 'followers', type_='foreignkey')
    op.drop_constraint(op.f('followers_subscriber_fkey'), 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'users', ['subscriber_id'], ['id'], ondelete='CASCADE')
    op.drop_column('followers', 'channel')
    op.drop_column('followers', 'isSubscribed')
    op.drop_column('followers', 'subscriber')
    op.add_column('groups', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('groups_admin_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_column('groups', 'admin')
    op.add_column('messages', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('messages_sender_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_groups_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_receiver_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'receiver')
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'messages')
    op.drop_column('messages', 'groups')
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index('ix_posts_author_created', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.drop_constraint(op.f('posts_author_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_fkey'), 'posts', 'users', ['author'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index('ix_posts_author_created', table_name='posts')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'author_id')
    op.add_column('messages', sa.Column('groups', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('messages', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sender', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('receiver', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_receiver_fkey'), 'messages', 'users', ['receiver'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('messages_groups_fkey'), 'messages', 'groups', ['groups'], ['id'])
    op.create_foreign_key(op.f('messages_sender_fkey'), 'messages', 'users', ['sender'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'group_id')
    op.drop_column('messages', 'receiver_id')
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'message')
    op.add_column('groups', sa.Column('admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_admin_fkey'), 'groups', 'users', ['admin'], ['id'], ondelete='CASCADE')
    op.drop_column('groups', 'admin_id')
    op.add_column('followers', sa.Column('subscriber', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('followers', sa.Column('isSubscribed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('followers', sa.Column('channel', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(op.f('followers_subscriber_fkey'), 'followers', 'users', ['subscriber'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('followers_channel_fkey'), 'followers', 'users', ['channel'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_channel_subscriber', 'followers', type_='unique')
    op.drop_index(op.f('ix_followers_subscriber_id'), table_name='followers')
    op.drop_index(op.f('ix_followers_channel_id'), table_name='followers')
    op.create_unique_constraint(op.f('unique_channel_subscriber'), 'followers', ['channel', 'subscriber'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_followers_subscriber'), 'followers', ['subscriber'], unique=False)
    op.create_index(op.f('ix_followers_channel'), 'followers', ['channel'], unique=False)
    op.drop_column('followers', 'is_subscribed')
    op.drop_column('followers', 'subscriber_id')
    op.drop_column('followers', 'channel_id')
    op.create_table('groupmembers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('groupmembers_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('groupmembers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('groupmembers_pkey'))
    )
    op.create_index(op.f('ix_groupmembers_group_id'), 'groupmembers', ['group_id'], unique=False)
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    # ### end Alembic commands ###
